image: ubuntu

stages:
  - run

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

backend:
  stage: run
  script:
    # - ssh trandotrungkien34@35.240.158.158 "cd flea_market && git checkout develop && git pull && docker compose -f docker-compose.yml up --build -d && docker image prune --force && exit"
     - ssh trandotrungkien34@35.240.158.158 "cd flea_market && git checkout develop && git pull && npm install && npm run build"
  only:
    - develop
